#!/bin/sh

set -e

if [ $CIRCLECI == 'true' ]; then
  echo "Packages needed are already installed, skipping."
elif systemd-detect-virt --container; then
  echo "Installing packages on docker container."
  apt-get update
  apt-get upgrade -y
  apt-get install -y \
      ca-certificates \
      git \
      libenchant1c2a \
      python3 \
      python3-pip \
      python3-venv
  rm -rf /var/lib/apt/lists/*
else
  echo "Installing packages on your local ubuntu machine."
  sudo apt-get install \
      libenchant1c2a \
      python3 \
      python3-pip \
      python3-venv
fi
