#!/bin/bash

set -e

# ubuntu dependencies
if [[ "$CIRCLECI" = "true" ]]; then
  apt-get update
  apt-get install -y python3 python3-venv python3-pip libenchant1c2a
else
  sudo apt-get install python3 python3-venv python3-pip libenchant1c2a
fi

python3 -m venv ./env

env/bin/python3 -m pip install --upgrade pip
env/bin/python3 -m pip install -r requirements.txt

echo "Remember to run source ./env/bin/activate now, and every time you start working"

# download curves
env/bin/python3 data/vex/download_curves.py
