#!/bin/sh

set -e

# Check format
if [ -z "`env/bin/python3 -m yapf --recursive --style pep8 --diff ./frc_rekt/ ./test/`" ]; then
    echo "YAPF formatted correctly."
else
    echo "YAPF formatting was not applied to commit. Run \`make prep\` to fix"
    exit 1
fi

env/bin/python3 -m pylint --rcfile=setup.cfg --reports=n ./frc_rekt/
env/bin/python3 -m pylint --rcfile=setup.cfg --reports=n \
    --disable=missing-docstring,protected-access,redefined-outer-name,invalid-name \
    ./tests/

env/bin/python3 -m pycodestyle ./frc_rekt ./tests/

env/bin/python3 -m pydocstyle ./frc_rekt

# pyclean
find . | grep -E "(__pycache__|\.pyc|\.pyo$)" | xargs rm -rf

env/bin/python3 -m pytest --color='yes' ./tests/
