#!/bin/bash

set -e

# Check format
if [ -z "`env/bin/yapf --recursive --style pep8 --diff ./frc_rekt/ ./test/`" ]; then echo "YAPF formatted."; else exit 1; fi

env/bin/pylint --rcfile=setup.cfg --reports=n ./frc_rekt/ ./tests/

env/bin/pycodestyle ./frc_rekt ./tests/

env/bin/pydocstyle ./frc_rekt

env/bin/pytest --color='yes' ./tests/
